# Generated by Django 4.2.16 on 2025-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbcxrapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientsmodel",
            old_name="address",
            new_name="p_address",
        ),
        migrations.RenameField(
            model_name="patientsmodel",
            old_name="name",
            new_name="p_name",
        ),
        migrations.RenameField(
            model_name="patientsmodel",
            old_name="status",
            new_name="p_status",
        ),
        migrations.AlterField(
            model_name="patientsmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
